version: "3.8"
services:
  backend:
    build: ./Endpoints
    ports:
      - "8000:80"
    volumes:
      - ./Endpoints:/var/www/html/
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
      MYSQL_DATABASE: penzi_db

  frontend:
    build: ./admin-dashboard # Or ./user-dashboard
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    image: mysql:5.7 # Or your preferred MySQL version
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: penzi_db
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: