version: '3.8'

networks:
  penzi-network:
    driver: bridge

services:
  backend:
    build:
      context: . 
      dockerfile: ./Endpoints/Dockerfile 
    ports:
      - "8000:80"
    volumes:
      - ./Endpoints:/var/www/html/
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: "rodney" 
      MYSQL_DATABASE: penzi_db
    restart: unless-stopped
    networks:
      - penzi-network

  admin-dashboard:
    build: ./admin-dashboard
    ports:
      - "3001:80"
    depends_on:
      - backend
    # volumes:
      # - ./admin-dashboard/build:/var/www/html/
    restart: unless-stopped
    networks:
      - penzi-network

  user-dashboard:
    build: ./user-dashboard
    ports:
      - "3002:80"
    depends_on:
      - backend
    # volumes:
    #   - ./user-dashboard/build:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - penzi-network

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rodney 
      MYSQL_DATABASE: penzi_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - penzi-network

volumes:
  db_data: