services:
  backend:
    build: ./Endpoints
    ports:
      - "8000:80"
    volumes:
      - ./Endpoints:/var/www/html/
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root  
      MYSQL_PASSWORD: ""   
      MYSQL_DATABASE: penzi_db
    restart: unless-stopped

  admin-dashboard:
    build: ./admin-dashboard
    ports:
      - "3001:80"
    depends_on:
      - backend
    volumes:
      - ./admin-dashboard/build:/var/www/html/
    restart: unless-stopped

  user-dashboard:
    build: ./user-dashboard
    ports:
      - "3002:80"
    depends_on:
      - backend

    volumes:
      - ./user-dashboard/build:/var/www/html/
    restart: unless-stopped

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: penzi_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
